apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionhistory
  namespace: transactionhistory
spec:
  selector:
    matchLabels:
      app: transactionhistory
  template: 
    spec: 
      containers:
      - name: transactionhistory
        image: gcr.io/krm-project88/cymbal-bank/release/transactionhistory:5749b9f
        env:
        - name: ENABLE_TRACING
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"